"""Shared event names without a runtime-package import dependency."""

from enum import Enum


class TaskEventType(str, Enum):
    """Auditable lifecycle and public progress event names."""

    TASK_CREATED = "task_created"
    TASK_QUEUED = "task_queued"
    TASK_STARTED = "task_started"
    TASK_COMPLETED = "task_completed"
    TASK_FAILED = "task_failed"
    TASK_CANCELLED = "task_cancelled"
    TASK_DEAD_LETTER = "task_dead_letter"
    LEASE_RENEWED = "lease_renewed"
    LEASE_EXPIRED = "lease_expired"
    EXECUTION_ABORTED = "execution_aborted"
    STALE_WORKER_REJECTED = "stale_worker_rejected"
    QUERY_PLANNING_STARTED = "query_planning_started"
    QUERY_PLANNING_COMPLETED = "query_planning_completed"
    INTENT_PLANNER_STARTED = "intent_planner_started"
    INTENT_PLANNER_SUCCEEDED = "intent_planner_succeeded"
    INTENT_PLANNER_FALLBACK = "intent_planner_fallback"
    QUERY_EXPANSION_STARTED = "query_expansion_started"
    QUERY_EXPANSION_SUCCEEDED = "query_expansion_succeeded"
    QUERY_EXPANSION_FALLBACK = "query_expansion_fallback"
    RETRIEVAL_STARTED = "retrieval_started"
    RETRIEVAL_COMPLETED = "retrieval_completed"
    QUERY_PLAN_AUDIT = "query_plan_audit"
    RETRIEVAL_RESULT_AUDIT = "retrieval_result_audit"
    RETRIEVAL_OVERLAP_AUDIT = "retrieval_overlap_audit"
    DEDUP_GROUP_AUDIT = "dedup_group_audit"
    DEDUP_GROUP_MEMBER_AUDIT = "dedup_group_member_audit"
    RESEARCH_INTENT_AUDIT = "research_intent_audit"
    RESEARCH_INTENT_TERM_AUDIT = "research_intent_term_audit"
    METADATA_CANDIDATE_AUDIT = "metadata_candidate_audit"
    METADATA_SUMMARY_AUDIT = "metadata_summary_audit"
    METADATA_FILTERING_STARTED = "metadata_filtering_started"
    METADATA_FILTERING_COMPLETED = "metadata_filtering_completed"
    PDF_PROCESSING_STARTED = "pdf_processing_started"
    PDF_PROCESSING_PROGRESS = "pdf_processing_progress"
    PDF_PROCESSING_COMPLETED = "pdf_processing_completed"
    PAPER_READING_STARTED = "paper_reading_started"
    PAPER_READING_PROGRESS = "paper_reading_progress"
    PAPER_READING_COMPLETED = "paper_reading_completed"
    READER_ITEM_STARTED = "reader_item_started"
    READER_ITEM_SUCCEEDED = "reader_item_succeeded"
    READER_ITEM_FAILED = "reader_item_failed"
    READER_STAGE_COMPLETED = "reader_stage_completed"
    READER_STAGE_ABORTED = "reader_stage_aborted"
    EVIDENCE_VERIFICATION_STARTED = "evidence_verification_started"
    EVIDENCE_VERIFICATION_PROGRESS = "evidence_verification_progress"
    EVIDENCE_VERIFICATION_COMPLETED = "evidence_verification_completed"
    FINAL_RELEVANCE_STARTED = "final_relevance_started"
    FINAL_RELEVANCE_COMPLETED = "final_relevance_completed"
    SURVEY_SYNTHESIS_STARTED = "survey_synthesis_started"
    SURVEY_SYNTHESIS_COMPLETED = "survey_synthesis_completed"
    ARTIFACT_EXPORT_STARTED = "artifact_export_started"
    ARTIFACT_EXPORT_COMPLETED = "artifact_export_completed"
    REPORT_QUALITY_ASSESSED = "report_quality_assessed"
    SURVEY_STAGE_STARTED = "survey_stage_started"
    SURVEY_SUBSTAGE_STARTED = "survey_substage_started"
    SURVEY_LLM_CALL_STARTED = "survey_llm_call_started"
    SURVEY_LLM_CALL_SUCCEEDED = "survey_llm_call_succeeded"
    SURVEY_LLM_CALL_FAILED = "survey_llm_call_failed"
    SURVEY_SUBSTAGE_COMPLETED = "survey_substage_completed"
    SURVEY_SUBSTAGE_FAILED = "survey_substage_failed"
    SURVEY_STAGE_COMPLETED = "survey_stage_completed"
    SURVEY_STAGE_ABORTED = "survey_stage_aborted"
    STAGE_FAILED = "stage_failed"
