"""Evidence-grounded structured research reporting."""

from .analysis_data import (
    ComparabilityAssessment,
    ComparabilityLevel,
    ComparisonCell,
    ComparisonColumn,
    ComparisonDataBuilder,
    ComparisonMatrixData,
    ComparisonRow,
    CrossPaperComparisonFacts,
    DeterministicTaxonomyBuilder,
    GroundingStatus,
    MethodFamily,
    MethodFamilyAssignment,
    MethodFamilyAssignmentDraft,
    MethodFamilyDraft,
    MethodTaxonomy,
    SupportLevel,
    SurveyAnalysisData,
    SurveyAnalysisDataBuilder,
    TaxonomyAssessment,
    TaxonomyContext,
    TaxonomyContextBudget,
    TaxonomyContextBuilder,
    TaxonomyError,
    TaxonomyEvidenceCoverage,
    TaxonomyLLMOutput,
    TaxonomyService,
    TaxonomyValidator,
)
from .citations import (
    CitationEntry,
    CitationRegistry,
    CitationRegistryError,
    CorePaperProfile,
    EvidenceLedgerEntry,
    FishboneReadinessAssessment,
    LiteratureTimelineEntry,
    PublicReportCitationIndex,
    ReferenceEntry,
    ReferenceIntegrityValidator,
    SurveyEvidenceData,
    SurveyEvidenceDataBuilder,
    build_public_report_citation_index,
    citation_group,
    citation_token,
    public_citation_refs,
    resolve_statement_locators,
)
from .context import ReportContextBuilder
from .exceptions import (
    ReportContextBuildError,
    ReportContextError,
    ReportGenerationError,
    ReportingError,
    ReportSchemaValidationError,
    ReportVerificationError,
    ReportWriterError,
    ReportWritingError,
)
from .fishbone import TimelineFishboneRenderer
from .fonts import CJKFontResolutionError, CJKFontResolver
from .models import (
    ReportCitation,
    ReportClaim,
    ReportContext,
    ReportEvidenceContext,
    ReportPaperContext,
    ReportSection,
    ResearchReport,
)
from .pdf import SurveyPdfLayoutConfig, SurveyPdfRenderer
from .rendering import (
    SurveyHtmlRenderer,
    SurveyMarkdownRenderer,
    SurveyPresentationStrings,
    SurveyRenderFormat,
    SurveyRenderResult,
    SurveyRenderService,
)
from .service import EvidenceGroundedReportService
from .survey import (
    CitationSafeSurveyWriter,
    ClaimCertainty,
    FutureDirectionKind,
    LiteratureMethodFacts,
    PublicSurveyCitationValidator,
    StatementReference,
    SurveyClaim,
    SurveyClaimDraft,
    SurveyClaimType,
    SurveyContextBudget,
    SurveyFutureDirection,
    SurveyNarrativeDraft,
    SurveyPublicContentValidator,
    SurveyReport,
    SurveyReportAssembler,
    SurveyReportContext,
    SurveyReportContextBuilder,
    SurveyReportVerifier,
)
from .survey_runtime import ProductionSurveyReportService
from .synthesis import (
    CrossPaperClaimPolicy,
    FullSurveySynthesisService,
    ReportDensity,
    SurveyFigureSlot,
    SurveyFutureDirectionDraft,
    SurveyParagraph,
    SurveyParagraphDraft,
    SurveyReportSynthesisAssembler,
    SurveyReportSynthesisWriter,
    SurveySection,
    SurveyStageDraft,
    SurveySynthesisAssembler,
    SurveySynthesisConfig,
    SurveySynthesisVerifier,
    SurveySynthesisWriter,
    SurveyTable,
    SynthesisStage,
    SynthesisStageBudget,
    choose_report_density,
)
from .verifier import ReportVerifier
from .writer import StructuredReportWriter

__all__ = [
    "EvidenceGroundedReportService",
    "ProductionSurveyReportService",
    "ClaimCertainty",
    "CitationSafeSurveyWriter",
    "LiteratureMethodFacts",
    "StatementReference",
    "SurveyClaim",
    "SurveyClaimDraft",
    "SurveyClaimType",
    "SurveyContextBudget",
    "SurveyNarrativeDraft",
    "SurveyReport",
    "SurveyReportAssembler",
    "SurveyReportContext",
    "SurveyReportContextBuilder",
    "SurveyPublicContentValidator",
    "PublicSurveyCitationValidator",
    "SurveyReportVerifier",
    "CitationEntry",
    "CitationRegistry",
    "CitationRegistryError",
    "PublicReportCitationIndex",
    "CorePaperProfile",
    "EvidenceLedgerEntry",
    "FishboneReadinessAssessment",
    "LiteratureTimelineEntry",
    "ReferenceEntry",
    "ReferenceIntegrityValidator",
    "SurveyEvidenceData",
    "SurveyEvidenceDataBuilder",
    "citation_group",
    "citation_token",
    "public_citation_refs",
    "build_public_report_citation_index",
    "resolve_statement_locators",
    "ReportCitation",
    "ReportClaim",
    "ReportContext",
    "ReportContextBuildError",
    "ReportContextBuilder",
    "ReportContextError",
    "ReportEvidenceContext",
    "ReportPaperContext",
    "ReportGenerationError",
    "ReportingError",
    "ReportSchemaValidationError",
    "ReportSection",
    "ReportVerificationError",
    "ReportVerifier",
    "ReportWritingError",
    "ReportWriterError",
    "ResearchReport",
    "StructuredReportWriter",
    "ComparisonCell", "ComparisonColumn", "ComparisonDataBuilder", "ComparisonMatrixData", "ComparisonRow",
    "ComparabilityAssessment", "ComparabilityLevel", "CrossPaperComparisonFacts", "DeterministicTaxonomyBuilder",
    "GroundingStatus", "MethodFamily", "MethodFamilyAssignment", "MethodFamilyAssignmentDraft", "MethodFamilyDraft", "SurveyAnalysisDataBuilder",
    "MethodTaxonomy", "SupportLevel", "SurveyAnalysisData", "TaxonomyAssessment", "TaxonomyContext",
    "TaxonomyContextBudget", "TaxonomyContextBuilder", "TaxonomyLLMOutput", "TaxonomyService", "TaxonomyValidator",
    "TaxonomyEvidenceCoverage", "TaxonomyError", "FutureDirectionKind", "SurveyFutureDirection",
    "CrossPaperClaimPolicy", "FullSurveySynthesisService", "ReportDensity", "SurveyFigureSlot", "SurveyParagraph", "SurveyParagraphDraft",
    "SurveyReportSynthesisAssembler", "SurveyReportSynthesisWriter", "SurveySection", "SurveyStageDraft",
    "SurveySynthesisAssembler", "SurveySynthesisConfig", "SurveySynthesisVerifier", "SurveySynthesisWriter",
    "SynthesisStage", "SynthesisStageBudget", "SurveyTable", "choose_report_density",
    "SurveyFutureDirectionDraft",
    "SurveyHtmlRenderer", "SurveyMarkdownRenderer", "SurveyPresentationStrings", "SurveyRenderFormat", "SurveyRenderResult", "SurveyRenderService",
    "TimelineFishboneRenderer", "SurveyPdfLayoutConfig", "SurveyPdfRenderer",
    "CJKFontResolutionError", "CJKFontResolver",
]
