"""Public runtime configuration, health, and CLI entry interfaces."""

from .cli import build_parser, main, run_cli
from .exceptions import (
    RuntimeConfigurationError,
    RuntimeErrorBase,
    RuntimeHealthError,
)
from .health import check_runtime_health
from .host import (
    CURRENT_SCHEMA_VERSION,
    DeadLetterService,
    DeadLetterServiceProtocol,
    DeadLetterTask,
    HostStatus,
    LeaseLossReason,
    LeaseMonitorProtocol,
    LeaseRenewalResult,
    PersistentTaskHostClient,
    RuntimeHostMetadata,
    RuntimeMetrics,
    RuntimeRecoveryProtocol,
    RuntimeRecoveryResult,
    RuntimeRecoveryService,
    SchemaMigrationError,
    TaskEvent,
    TaskEventType,
    TaskHost,
    TaskHostAlreadyRunningError,
    TaskHostError,
    TaskHostUnavailableError,
    TaskLease,
    WorkerLeaseMonitor,
    create_task_host_client,
)
from .metrics import (
    MetricsExporter,
    MetricsExporterProtocol,
    RuntimeMetricsSnapshot,
)
from .models import HealthCheckResult, HealthReport, HealthStatus
from .settings import RuntimeSettings

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "DeadLetterTask",
    "DeadLetterService",
    "DeadLetterServiceProtocol",
    "HealthCheckResult",
    "HealthReport",
    "HealthStatus",
    "HostStatus",
    "LeaseLossReason",
    "LeaseMonitorProtocol",
    "LeaseRenewalResult",
    "MetricsExporter",
    "MetricsExporterProtocol",
    "PersistentTaskHostClient",
    "RuntimeConfigurationError",
    "RuntimeErrorBase",
    "RuntimeHealthError",
    "RuntimeHostMetadata",
    "RuntimeMetrics",
    "RuntimeMetricsSnapshot",
    "RuntimeRecoveryResult",
    "RuntimeRecoveryProtocol",
    "RuntimeRecoveryService",
    "SchemaMigrationError",
    "RuntimeSettings",
    "TaskHost",
    "TaskHostAlreadyRunningError",
    "TaskHostError",
    "TaskHostUnavailableError",
    "TaskEvent",
    "TaskEventType",
    "TaskLease",
    "WorkerLeaseMonitor",
    "build_parser",
    "check_runtime_health",
    "create_task_host_client",
    "main",
    "run_cli",
]
